jobs:
  CloneRepo:
    uses: git-checkout@v1
    with:
      url: https://github.com/Jameshskelton/workflow-test.git
    outputs:
      repo:
        type: volume
    resources:
      instance-type: C5
  TrainModel:
    uses: script@v1
    with:
      image: tensorflow/tensorflow:1.14.0-gpu-py3
      script: |-
        pip3 install -U scikit-learn
        pip3 install pandas
        cd /inputs/repo
        python3 trainModel.py 
        mv save.p /outputs/save
    needs:
      - CloneRepo
    inputs:
      repo: CloneRepo.outputs.repo
    outputs:
      save:
        type: volume
    resources:
      instance-type: C5
  workflow-test:
    uses: script@v1
    with:
      image: tensorflow/tensorflow:1.14.0-gpu-py3
      script: |-
        pip3 install -U scikit-learn
        pip3 install pandas
        mv /inputs/save/save.p /inputs/repo
        cd /inputs/repo
        python3 model_iris.py 
        mv predSpecies1.csv /outputs/iris
        ls "-aFlR" /outputs/iris
    needs:
      - CloneRepo
      - TrainModel
    inputs:
      repo: CloneRepo.outputs.repo
      save: TrainModel.outputs.save
    outputs:
      iris:
        type: dataset
        with:
          ref: dst5ycz7ehnkv5u
    resources:
      instance-type: C5